### ISSUE TITLE
[suggestion] Adding paxels/AIOTs

### ISSUE THREAD

**Issue by DanMeadWasTaken** [SigmundGranaas/forgero#448] opened 2023-02-15 18:23 UTC
Basically, adding tools such as a paxel or AIOT

These could require the tool heads for all the included tools- so a paxel could require a pickaxe head/ shovel head/ axe head and 2-3 bindings? and depending on the material used for each would change the durability as a whole. and the material used for each would change it's ability to dig materials of that type. 

so a diamond pickaxe/ironshovel/goldaxe would mine obsidian, but mine wood and dirt as fast as their respective materials would otherwise?

**Comment by Steveplays28** [comment] 2023-02-15 18:53
Just saw this is actually a duplicate of #150.
Your suggestions are definitely nice to keep in mind though, thanks.

**Closed as not planned by Steveplays28** 2023-02-15 18:53 UTC
Labels: new feature

**Comment by DanMeadWasTaken** [comment] 2023-02-15 18:59
Ah my bad- I had searched for AIOT and paxel but hadn't found anything in the issues page. guess i should've manually looked through lol

**Comment by Steveplays28** [comment] 2023-02-15 19:00
No worries, those two keywords weren't in the title before. Just updated the title of the other issue to include those two keywords. 

Didn't see it until just now either, only saw it because I'm going through and updating/cleaning up all the older issues.
Thanks for the interest though!

**Comment by SigmundGranaas** [comment] 2023-02-15 21:05
Just a small update on the multi-head discussion. Technically everything that needs to be done system-wise is in place to support multi-head tools. My approach would be special head schematics that produce a part head with an available slot that can be filled by a second head, this way you can combine two tools into one.

Tool effectiveness is done completely dynamically now, and is handled entirely by data properties. By default each schematic adds effectiveness for their vanilla counterpart to keep things consistent. I you wanted to, you could create a paxel schematic with all the effectiveness to create an all-in-one-tool. I'll probably look at this in the future but for now, the option to create this lies with whoever wants to do it.
