### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Rogenar** [SigmundGranaas/forgero#656] opened 2023-07-13 11:41 UTC
[latest.log](https://github.com/SigmundGranaas/forgero/files/12038909/latest.log)
[rei.log](https://github.com/SigmundGranaas/forgero/files/12038910/rei.log)
[rei-issues.log](https://github.com/SigmundGranaas/forgero/files/12038911/rei-issues.log)
[crash-2023-07-13_14.34.41-client.txt](https://github.com/SigmundGranaas/forgero/files/12038912/crash-2023-07-13_14.34.41-client.txt)
The game crashes. The language of the game is Turkish.

**Comment by SigmundGranaas** [comment] 2023-07-13 14:30
This is a duplicate of #594. The error remains the same, and I have no idea what is causing the trinket identifier to be modified when using Turkish as the game language.

**Closed as not planned by SigmundGranaas** 2023-07-13 14:30 UTC
