### ISSUE TITLE
Causes Cobblemon/Architectury and Mythic Metals/OωO to become unstable

### ISSUE THREAD

**Issue by UnusedCactus** [SigmundGranaas/forgero#253] opened 2022-12-23 17:53 UTC
For some reason, installing this mod has caused Cobblemon and Mythic Metals to become unstable.

### Cobblemon:
Pokemon battles do not start properly, and can thus never end. If the player leaves the game in this state the game crashes.
Crash log suspects Cobblemon and Architectury.
[crash-2022-12-23_10.37.14-server.txt](https://github.com/SigmundGranaas/forgero/files/10296538/crash-2022-12-23_10.37.14-server.txt)

### Mythic Metals
Ores cannot be smelted in a furnace/blast furnace. The game crashes when trying to open a forge's menu.
Crash log suspects OωO and Alloy Forgery.
[crash-2022-12-23_12.30.31-client.txt](https://github.com/SigmundGranaas/forgero/files/10296551/crash-2022-12-23_12.30.31-client.txt)

[latest.log](https://github.com/SigmundGranaas/forgero/files/10296567/latest.log)
(Important info starting at lines 4385, 6363) Thank goodness for Not Enough Crashes. Only one log for all of this.

**Comment by SigmundGranaas** [comment] 2022-12-23 19:14
Thanks for the report! 
I'll look through the issues and try to replicate them to find a fix. Are these mods part of any pack that I should test, or are these custom lists? Crash logs definitely looks weird as they don't mention any issues caused by Forgero, but hopefully I can replicate the issues based on your description.

**Comment by SigmundGranaas** [comment] 2022-12-23 19:35
I tried creating a new run config with:

  [✔] architectury-6.4.62-fabric
  [✔] cloth-config-8.2.88-fabric
  [✔] fabric-api-0.69.0+1.19.2
  [✔] forgero-fabric-full-0.10.1-BETA-1.19.2
  [✔] mythicmetals-0.16.4+1.19.2
  [✔] owo-lib-0.9.3+1.19
  [✔] RoughlyEnoughItems-9.1.580
  [✔] sodium-fabric-mc1.19.2-0.4.4+build.18
  [✔] wraith-alloy-forgery-2.0.17+1.19
  
 But were unfortunately unable to replicate the Mythic metals issue, as all of the furnaces and forges worked as intended. it might have something to do with the other mods in your list as well, so I'll have to try this one again if I can install the whole list.
 
 But I see that you are using version 0.10.0 in the mythic metals setup. It had some issues, so if you can try updating to 0.10.1, and checking again, that would nice.

**Comment by SigmundGranaas** [comment] 2022-12-23 19:52
For the Cobblemon situation I ran a config with:

Mods:
  [✔] architectury-6.4.62-fabric
  [✔] cloth-config-8.2.88-fabric
  [✔] Cobblemon-fabric-1.1.1+1.19.2
  [✔] fabric-api-0.69.0+1.19.2
  [✔] forgero-fabric-full-0.10.1-BETA-1.19.2
  [✔] mythicmetals-0.16.4+1.19.2
  [✔] owo-lib-0.9.3+1.19
  [✔] RoughlyEnoughItems-9.1.580
  [✔] sodium-fabric-mc1.19.2-0.4.4+build.18
  [✔] wraith-alloy-forgery-2.0.17+1.19
  
  But unfortunately I couldn't recreate the issue here either. I started the game, chose a pokemon, and did a couple of fights, but none of them caused any issues. Are there special situations where it hangs the battles, or did this happen every time in your configuration?

**Comment by UnusedCactus** [comment] 2022-12-25 13:00
The battle issue happened every time I tried to start a battle. I can get some images of the issue later if you want.

**Comment by SigmundGranaas** [comment] 2022-12-25 14:57
Yeah that would be great! Anything that makes it easier to replicate the issue is nice. Did you test the MM issue with a new version of Forgero? If it still causes issues, there might be another mod causing stability issues between MM/cobblemon and Forgero, maybe something with tags and resources not being ordered correctly, in which case I'll have to investigate further and expand the configuration with more relevant mods.

**Comment by UnusedCactus** [comment] 2022-12-30 23:34
Sorry, I haven't been in town recently so I haven't been able to test stuff out, however I do have the screenshots.
![2022-12-26_10 30 52](https://user-images.githubusercontent.com/87100678/210117982-ab7756a1-6d29-4d52-b01c-f40a53819aa6.png)
![2022-12-26_10 30 36](https://user-images.githubusercontent.com/87100678/210117985-a8b59a43-fe19-4d9a-a6f7-a5bdf614d5db.png)
The bug seems to just happen randomly. I'll test the new versions and get back to you.

**Comment by SigmundGranaas** [comment] 2023-01-03 09:21
Great! Looking forward to tests with the new versions. It would be awesome to get the issues resolved!

**Comment by SigmundGranaas** [comment] 2023-03-05 08:54
I'll close this issue for now. Feel free to repoen it if the issue persists

**Closed as not planned by SigmundGranaas** 2023-03-05 08:54 UTC
Labels: bug, question, compatibility, needs testing
