### ISSUE TITLE
[1.20.4] Forgero uses ARRP built in which is broken

### ISSUE THREAD

**Issue by Official-V-Zer0** [SigmundGranaas/forgero#1114] opened 2024-10-22 19:59 UTC
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'advanced_runtime_resource_pack' at 'net.devtech.arrp.ARRP'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'advanced_runtime_resource_pack' at 'net.devtech.arrp.ARRP'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 2 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'advanced_runtime_resource_pack'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.devtech.arrp.ARRP failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 4 more
Caused by: java.lang.UnsupportedClassVersionError: net/frozenblock/lib/shadow/blue/endless/jankson/JsonGrammar has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at knot//net.frozenblock.lib.config.api.instance.json.JsonType.<clinit>(JsonType.java:26)
	at knot//net.frozenblock.wilderwild.config.WWMixinsConfig.<clinit>(WWMixinsConfig.java:35)
	at knot//net.frozenblock.wilderwild.mixin.WilderWildMixinPlugin.onLoad(WilderWildMixinPlugin.java:40)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:790)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 13 more

ARRP is broken and causes my 440 map modpack to not launch playable

**Comment by JorisDeBeer** [comment] 2024-10-22 20:13
Are you adding ARRP manually? because that causes crashes yea

**Comment by Official-V-Zer0** [comment] 2024-10-22 20:16
No, arrp is not added manually. The Arrp that is added is the one that is baked into forgero

**Comment by SigmundGranaas** [comment] 2024-10-22 20:25
Caused by: java.lang.UnsupportedClassVersionError: net/frozenblock/lib/shadow/blue/endless/jankson/JsonGrammar has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

This issue is not from ARRP. Another mod has been compiled and released with a newer java version (java 21)

**Comment by Official-V-Zer0** [comment] 2024-10-22 20:39
Ok. is there a solution to make it work?

**Comment by SigmundGranaas** [comment] 2024-10-22 23:04
Either update your Java to 21 and disable java version check in whatever launcher you're using, or find whichever mod is depending on the Frozenblock lib mod which is bringing in the 1.21 version of this mod: https://github.com/FrozenBlock/Jankson-ML/tree/1.21, and remove it.

**Comment by SigmundGranaas** [comment] 2024-10-22 23:05
I will close this, as I don't see how this is connected to Forgero, unless the crashing issue is solved by removing only Forgero from the mod list.

**Closed as completed by SigmundGranaas** 2024-10-22 23:05 UTC

**Comment by Official-V-Zer0** [comment] 2024-10-22 23:44
I know it's completed but I do wanna mention that like ARRP, it seems Frozenblock is a baked in mod so it's impossible to replace it as it's in the processedmods folder.

**Comment by Official-V-Zer0** [comment] 2024-10-22 23:44
But I'll try updating Java even though I did recently

**Comment by Official-V-Zer0** [comment] 2024-10-23 17:28
For some dumb reason, Modrinth did not use the Java 21 version but instead the 17 version. So that fixed it simply. Thanks Sigmund
