### ISSUE TITLE
Dying Arrow Parts causes Server Crash

### ISSUE THREAD

**Issue by callmeMaevey** [SigmundGranaas/forgero#899] opened 2024-04-20 18:35 UTC
[crash-2024-04-20_18.14.37-server.txt](https://github.com/SigmundGranaas/forgero/files/15049389/crash-2024-04-20_18.14.37-server.txt)

I had a player report this crash.

Steps to reproduce:
 They tried to dye a lapis handle pink in the upgrade station on an arrow with a amethyst head
 
Stack Trace:
  see attached file
 
  
Result:
   Server crash; on reboot the server and the item had been deleted - no loss of data and server is healthy.

**Comment by SigmundGranaas** [comment] 2024-04-22 17:58
Thanks for the report! I'll try to reproduce and see if I can find the issue, although the crash log does not reference any Forgero code so I suspect this might be an incompatibility with another mod if it is caused by Forgero.

The crash report references Cardinal components and Travelers backpack. I'll test with those mods as well to see if I can reproduce.

**Comment by SigmundGranaas** [comment] 2024-04-22 19:29
It seems like dying a mastercrafted handle on an arrow causes something to break which removes the item. This should be fixed, but the crash only happens with Traveler's backpack installed. Wierd.

**Closed as completed** 2024-04-26 14:18 UTC
Labels: bug, crash
