### ISSUE TITLE
1.19.2 client crash

### ISSUE THREAD

**Issue by netcore10** [SigmundGranaas/forgero#488] opened 2023-02-28 13:12 UTC
https://mclo.gs/Ngth0a7

1.19.2 ... quilt 18.2

**Comment by Steveplays28** [comment] 2023-02-28 13:15
Duplicate of #432. Issue should be fixed with the release of the next `0.10.7` release candidate.

**Comment by SigmundGranaas** [comment] 2023-02-28 13:15
This issue was fixed by #480 
This crash will be fixed by the upcoming 0.10.7

**Closed as not planned by Steveplays28** 2023-02-28 13:15 UTC
Labels: bug, crash

**Comment by SigmundGranaas** [comment] 2023-02-28 13:18
Also, I would like to take this opportunity to mark my answer as a duplicate of Steve's.

**Comment by netcore10** [comment] 2023-02-28 13:35
Apologies, i didn't know.

**Comment by Steveplays28** [comment] 2023-02-28 13:59
No worries!
